iocBoot/iocNoAsyn/st.cmd.Vx
Update "iocBoot/iocNoAsyn/st.cmd.Vx" comments for valid MAXv IRQ's are 2-6.
=> Document valid MAXv IRQ's are 2-6

motorApp/PIGCS2Src/PIasynAxis.cpp, motorApp/PIGCS2Src/PIasynController.cpp
Replaced motorAxisHasClosedLoop with pController_->motorStatusGainSupport_ in calls to setIntegerParam()
Fixes #22
=> Corrected setIntegerParam() calls in PIasyn{Axis,Controller}.cpp

motorApp/NewportSrc/XPSAxis.cpp
This fixes a problem introduced in the motor record to do with issuing stops when the record has the RA_PROBLEM bit set. This broke the home function for the XPS controller, because we have to re-home from a problem state. The motor record was issuing a stop as soon as the home function completed, causing the home procedure on the XPS to fail.
=> Clear the problem bit in MSTA as part of the home function.

motorApp/MotorSrc/asynMotorAxis.h
The asynMotorController and asynMotorAxis use a hacky workaround to allow developers to not have to write pC_-> in front of all their setXXXXParam calls. This unfortunately causes the asynMotorController to not work correctly if outside code tries to set the motor status or position. Normally, this doesn't matter because the only code changing those parameters is the motor axis. However, I have run into an issue where a motor axis will be calling an outside function that identifies an asyn port and attempts to set parameters. The current setup of the asynMotorController/Axis precludes this ability. 
Ideally, the asynMotorController and Axis would be rewritten to work like a standard asynPortDriver in all instances. But, since the Polling Thread and all Gen3 drivers expect the current …
=> Switch asynMotorAxis status_ and statusChanged_ to be protected

motorApp/MotorSrc/motorRecord.cc, motorApp/MotorSrc/motorRecord.dbd
When a soft motor record is driving a database, it's sometimes desirable for the database to be able to implement SET/USE operations, instead of having the soft motor record do them internally.  When IGSET==1, the motor record will behave as though SET==0, no matter what the actual value of SET is.  Then the database can monitor the SET field, and handle any changes to VAL while SET==1 as it wishes - for example, by forwarding them to a downstream hard motor.
=> ignore SET field, so a database can do it instead

configure/RELEASE, iocBoot/iocWithAsyn/motor.substitutions.script, iocBoot/iocWithAsyn/scripts/softMotor.lua, iocBoot/iocWithAsyn/scripts/vmc.lua, iocBoot/iocWithAsyn/st.cmd.script, motorApp/Db/Makefile, motorApp/Db/ScriptMotorReload.db, motorApp/Makefile, motorApp/ScriptMotorSrc/Makefile, motorApp/ScriptMotorSrc/ScriptMotorDriver.cpp, motorApp/ScriptMotorSrc/ScriptMotorDriver.dbd, motorApp/ScriptMotorSrc/ScriptMotorDriver.h, motorApp/op/adl/ScriptMotorReload.adl, motorExApp/WithAsyn/Makefile
This pull request adds a Model 3 driver that runs functions from a lua scripting language file. 
Having a single motor driver than can run code from an easily modifiable text file grants a lot of benefits. 
- All the background C code (include headers, constructors, function registration) no longer has to be copied between new drivers, leading to a drastically reduced file footprint (a 500 line driver down to ~50).  
- Due to the ability to reload support on the fly, a developer doesn't have to rebuild and reboot an IOC to see changes to their driver, leading to a drastically shortened development cycle.
- And since nothing needs to be compiled, support can easily be customized or modified for an IOC as the need arises. If a vendor releases a motor that's just slightly different than …
=> Scriptable Motor Controller

.ci/travis-prepare.sh, .travis.yml
(Second attempt after a nice discussion in #71)
Builds from source and caches the following:
- EPICS base (3.14, 3.15, 3.16 - shared and static)
- IPAC 2.14 (except on Windows)
- Sequencer 2.2.4
- Asyn 4-31
Specific combinations and versions of these are configurable through the environment variables, using @mdavidsaver's handy template. Caching is per each set of environment variables, so no special directory names are necessary.
It's certainly not as comprehensive as it could be (lacking VxWorks and OSX builds), but it will catch compilation errors in many common configurations.
As an aside: Beside for my belief that CI is generally a good thing, I'm also trying to push this issue as I have about 10 PRs I'd like to send in soon from past SLAC motor record changes.
=> Add TravisCI configuration (3.14 - 3.16, Linux/RTEMS/mingw32)

motorApp/MotorSrc/motorRecord.cc
> Previously ACCL was only calculated as (VELO-VBAS)/TIME.
> This could cause problems for drivers setting ACCL=0.
> Now if VELO == VBAS, ACCL = VELO/TIME.
cc @jmdewart
(Note: This is the first of a few SLAC internal motor-record changes that I'm trying to bring back to the collaboration. I'll be CC'ing those who I believe are the original authors in each PR.)
=> Fix ACCL calculation when VELO == VBAS.

motorApp/NewportSrc/devESP300.cc, motorApp/NewportSrc/drvESP300.cc
Problem with devESP300.cc
- The ESP300 has independent settings for the acceleration and deceleration.  These are set with the AC and AG commands respectively.  However, when setting the acceleration device support was previously only sending AC, not AG.  Thus the deceleration value used was whatever was saved in the ESP300 non-volatile settings.  This fix sends the AG command with the same value as the AC command.
Problem with drvESP300.cc
- The drive_resolution variable in the driver is used to convert from motor record steps to controller engineering units.  Previously drive_resolution was being set by reading the value of the SU? command.  This returns the encoder resolution.  However, for open-loop stepper motors this value is not defined, and I could find no way to set it in the …
=> Fix problems with devESP300 and drvESP300

documentation/motorRecord.html, iocBoot/iocWithAsyn/motor.cmd.ANF2, iocBoot/iocWithAsyn/motor.substitutions.ANF2, motorApp/AMCISrc/AMCISupport.dbd, motorApp/AMCISrc/ANF2Driver.cpp, motorApp/AMCISrc/ANF2Driver.h, motorApp/AMCISrc/ANF2Support.dbd, motorApp/AMCISrc/Makefile, motorApp/AMCISrc/README_ANF2.md, motorApp/Db/ANF2Aux.template
Added support for the following models of [AMCI ANF controllers](https://www.amci.com/plc-automation-products/anf1-anf2-anynet-io-motion-controller-networked-io):
* ANF1E
* ANF1
* ANF2E
* ANF2
=> Added support for AMCI ANF controllers

motorApp/MicronixSrc/MMC200Driver.cpp
In testing an MMC-200 connected via USB, this added flush helped make sure the initial 'VER?' query went through properly.
=> Added I/O flush before first query (Micronix MMC-x00)

motorApp/MotorSrc/motorRecord.cc
Fix the problem that the record gets stuck when STOP is
pressed while the record is in MIP_DELAY (and the motor
is standing still, so that there is no record processing).
Currently the MIP_DELAY bits are set to 0, when a STOP is issued.
As the motor already hase stopped, the DMOV field never goes to 1.
There are 2 possible solutions here:
a) STOP wins:
pmr->dmov = FALSE;
MARK(M_DMOV);
b) DELAY wins
Send a STOP to the controller (just to be sure), but wait for the DELAY.
a) may cause probles later, whena new positionioning is done after the STOP
and a new DELAY is triggered.
As the old callback is still active, it may be executed before the new
callback. And the time will be too short.
For this reason go with b)
http://www.aps.anl.gov/epics/tech-talk/2015/msg01786.php
=> Record: motor record DLY and STOP problem

motorApp/OmsAsynSrc/omsBaseAxis.cpp, motorApp/OmsAsynSrc/omsBaseAxis.h
Our motor position was often not synchronized with the encoder position, resulting in very erratic behavior once the encoder was used. This fixed it.
I'm not entirely sure this was the best place to apply this synchronization - if there's a better place, please do tell!
=> OMS: Synchronize motor position with encoder position before every move

motorApp/MotorSrc/motorRecord.cc
In case when move is triggered by external program (not motor record) limit switches status should also be updated.
(comment edited on 1.9.2016)
This fixes issue #35
=> Status of limit switches updated independent of movement direction.

motorApp/MotorSrc/motorRecord.cc
The following situation came up while debugging soft limits in a
motion controller which had different values then the record.
The motor is at position 50mm (RBV=50), the low soft limit is 15 (LLM=15),
jogging velocity is 10 mm/sec (JVEL=10).
The motion controller has an internal soft limit which is 35 mm, which
we want to test.
Set JOGR to 1, the motor will move backwards.
(Side note: it would be stopped by the record once it passed 25mm).
Before that, the motion controller stops the motor internally and reports DONE.
The state machine in the record is not prepared to handle this and JOGR stays 1.
The expected behavior is that JOGR returns to 0.
Because this is an unexpected stop, reset even pending home requests.
In other words: call clear_buttons(pmr)
Whether or not an alarm is raised …
=> Record recognizes motor stop while jogging

motorApp/MotorSrc/motorRecord.cc
Partially reverts commit 303a9208e368ef07839afff67bac69e429af7332
Fixes issue #100:
> There have been multiple problems caused by the motor record sending a stop when the problem bit is set.
>
> One problem is discussed here:
> https://epics.anl.gov/tech-talk/2018/msg01338.php
>
> The commit that introduced the stop is 303a920. I vaguely recall the change being a workaround for less-than-idea behavior of a motor controller, but neither @rsluiter nor I remember which controller that was.
>
> Motor drivers should be modified to send the stop command when the condition that triggers the setting of the problem bit is detected, if needed.
=> Don't set "stop" field true if driver returns RA_PROBLEM true

docs/motorRecord.html, motorApp/MotorSrc/motorRecord.cc, motorApp/MotorSrc/motorRecord.dbd
This is from Matthew Pearson, pearsonmr@ornl.gov
A number of users and staff have requested that the motor record have a
setpoint deadband field (eg. SPDB), which prevents any motion from
happening if the readback position is within SPDB.
Without a SPDB we have issues with motors moving unnecessarily.
For example, if the RBV is 0.001 and we set VAL to 0.0, if we have a
non-zero backlash correction then the motor will move unnecessarily
to take out backlash.
Even without backlash correction we often enable and disable the
drive amplifier for no good reason.
Currently the effective setpoint deadband is equal to MRES,
but this is often too small to be an effective setpoint deadband.
The new SPDB field would default to 0.0
The new code hooks into do_work():
When the new setpoint is within …
=> Add field SPDB, "Set Point Dead Band"

motorApp/NewportSrc/HXPDriver.cpp, motorApp/NewportSrc/HXPDriver.h
Issue 124 description:
Older versions of the HXP firmware (v2.1.0 and earlier) are able to query the positions of the virtual axes independently using the virtual group names.  Newer versions of the firmware (confirmed with v3.1.0) return an error (-19: GroupName doesn't exist or unknown command).  Querying the positions of all six virtual axes simultaneously works on both v2.1.0 and v3.1.0.
Fixes #124
=> Moved the polling from HXPAxis::poll to HXPController::poll

motorApp/Db/Makefile
Added Makefile rules to allow installation of *.req files in into motor's top-level db dir when building against EPICS base 3.14.  Updated motorAerotech and motorNewport to add the build rule to the Makefile in their Db dirs.
=> Added Makefile rules to allow building against base 3.14

docs/RELEASE.txt, motorApp/MotorSrc/motordrvCom.cc, motorApp/MotorSrc/motordrvCom.h
The 2nd and 3rd parameter in send_mess() can and should
be a 'const char *' instead of just 'char *'.
Modern compilers complain here, so that the signature now
gets the const.
Update drivers from the following list to use the new send_mess():
modules/motorAcs
modules/motorAcsTech80
modules/motorAerotech
modules/motorFaulhaber
modules/motorIms
modules/motorKohzu
modules/motorMclennan
modules/motorMicos
modules/motorMicroMo
modules/motorNewFocus
modules/motorNewport
modules/motorOms
modules/motorOriel
modules/motorPI
modules/motorParker
modules/motorPiJena
modules/motorSmartMotor
modules/motorThorLabs
And while there, fix one more "const char *" in motordrvCom.cc
=> send_mess() uses 'const char *' (and more const char*)

configure/RELEASE
Reverted the commit that caused issue 149 and updated the driver modules' EXAMPLE_RELEASE.local files to avoid problems when building them outside the motor tree.
Fixes #149
=> Fix for issue 149

motorApp/op/adl/motorxU.adl
Lower the cosmetic rectangle in `motorxU.adl` to expose tweak controls, which fixes #154.
=> Lower the cosmetic rectangle in motorxU.adl

.ci-local/travis/post-prepare.sh
When grepping for SUPPORT in the different files,
grep may fail, because "SUPPORT" is not present.
A failing grep will cause travis to fail.
Solution: Ugnore the exit code of grep.
=> travis/post-prepare.sh: Ignore return code of grep

docs/motorRecord.html, motorApp/MotorSrc/devMotorAsyn.c, motorApp/MotorSrc/motorRecord.dbd, motorApp/MotorSrc/motordevCom.cc
Partly revert the following commit:
commit 3090983c313c57efdcd7c788ba234e775d300e06
Author: Ron Sluiter <rsluiter@users.noreply.github.com>
Date:   Wed Jul 29 15:50:23 2015 +0000
Bug fix for target position (VAL/DVAL/RVAL) initialization error
when the motor record is configured to do retries.
And from the release notes:
6) Kevin Peterson discovered an initialization bug when the motor record is
configured to do retries. When configured to do retries, the motor
record issues incremental rather than absolute moves. If the motor
behaves badly (e.g., a piezo stiction motor) the controller's absolute
step count can be far from its' absolute readback position. The motor
record initialization logic that determines how the target positions
are initialized at boot-up was not taking into …
=> Add field RSTM: Restore Mode

docs/motorRecord.html, motorApp/Db/asyn_motor.db, motorApp/Db/basic_motor_settings.req, motorApp/Db/motor.db
Autosave the RSTM field and allow it to be specified when motor records are loaded.
=> RSTM improvements

motorApp/MotorSrc/asynMotorAxis.h, motorApp/MotorSrc/asynMotorController.h
The new version of asyn does not use shareLib.h.  Thus we need to include shareLib.h in these files.
=> Add shareLib.h

motorApp/MotorSrc/motordrvCom.h
We can't compile motor against this commit of EPICS base:
commit 0f428ea3346d89719b03a6419319c85afb0fee13
Author: Michael Davidsaver <mdavidsaver@gmail.com>
Date:   Thu Apr 1 10:57:19 2021 -0700
use DBCORE_API
Solution: Include <shareLib.h>
=> motordrvCom.h needs shareLib.h

motorApp/MotorSrc/motorRecord.cc
When a database is loaded with UEIP=Yes and the controller says that there is no
encoder present, reset UEIP to False.
=> motorRecord: Reset UEIP to No if no encoder is present

motorApp/MotorSrc/motorRecord.cc
A negative BDST was correctly applied to negative direction moves
if moves are absolute. When retries are enabled all moves become
relative and backlash was not applied correctly for negative direction
moves.
See epics-modules/motor#181
=> Fix negative backlash with relative moves in a negative direction

docs/motorRecord.html
Most fields referring raw positions are wrongly documented as DOUBLE instead of LONG.
=> Doc: fix some field types according to motorRecord.dbd

motorApp/MotorSrc/motorRecord.cc, motorApp/MotorSrc/motorRecord.dbd
=> Add raw limits so that soft limits are synced with motor resolution change 

motorApp/MotorSrc/devMotorAsyn.c
When the motorRecord is initialized, init_record() is called.
For asynMotors init_record() calls init_controller() in devMotorAsyn.c
From here, the encoder ratio is send to the driver.
After doing that, the code "locks" the execution waiting for a callback
to call epicsEventSignal(pPvt->initEvent) which "unlocks" the code.
As Mark Clift points out, this code can be simplified and the initEvent
can be removed.
Mark Rivers suggested to use the asynFloat64SyncIO interface,
which locks the asyn port when calling the driver.
=> devMotorAsyn: remove initEvent in init_record()

docs/RELEASE.md
Updated motorNewFocus, motorNewport, and motorPI for fixes for 'make uninstall' removing iocsh files.  This also allows them to be installed to motor's top-level directory.
=> Updated driver modules for fixes for 'make uninstall' removing iocsh files.

motorApp/MotorSrc/motorRecord.dbd
Added prop(YES) to the PREC field and fields that should update when the PREC field changes in motorRecord.dbd.
Phoebus users can add the following line to the Phoebus settings.ini file:
```
org.phoebus.pv.ca/dbe_property_supported=true
```
Changes to the PREC field will be immediately reflected in Phoebus displays, without having to close and reopen them.
=> Added prop(YES) to motorRecord.dbd

.github/workflows/ci-scripts-build-full.yml, .github/workflows/ci-scripts-build.yml, motorApp/MotorSrc/motorRecord.cc
commit 24a53e660e213ae6a57dc4d6f5648bed895ef85e,
"motorRecord: Reset UEIP to No if no encoder is present"
Seems to have introduced a typo:
When ueip is reset to false, because there is no encoder, then db_post_events(ueip) should be called, not urip.
=> motorRecord.cc: Post ueip if reset to false when encoder missing

docs/motorDeviceDriver.html
Fix typos in `docs/motorDeviceDriver.html`.
=> Fix typos in motorDeviceDriver.html

motorApp/MotorSrc/motorRecord.cc
The following lead to an endless loop:
- move the motor by writing to the .VAL field
- while moving, home the motor using the HOMF field
- while still homing, write a different value to the VAL field.
The problem is that for "pmr->val != pmr->lval" the motorRecord is send into do_work() and a new HOME is started.
Solution:
Reset the HOMF and HOMR buttons.
=> motorRecord: prevent endless loop VAL-HOMF-VAL
